# Generated by Django 5.1.1 on 2024-11-15 11:15

import blog.validadores.validador_receta
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=50, verbose_name='unidad')),
                ('cantidad', models.FloatField(verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, validators=[blog.validadores.validador_receta.validar_solo_letras_con_espacio, blog.validadores.validador_receta.validate_no_html], verbose_name='nombre')),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), blog.validadores.validador_receta.validate_no_html], verbose_name='descripcion')),
                ('preparacion', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000), blog.validadores.validador_receta.validate_no_html], verbose_name='preparacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('puntuacion', models.FloatField(validators=[blog.validadores.validador_receta.validate_between_zero_and_five], verbose_name='puntuacion')),
            ],
        ),
    ]
