# Generated by Django 5.1.1 on 2024-11-23 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, to_field='cedula'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='ecommerce.producto'),
        ),
        migrations.AddField(
            model_name='receta',
            name='category',
            field=models.ManyToManyField(related_name='recetas', to='blog.category'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='blog.receta'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='blog.receta'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.receta', verbose_name='receta'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='cedula', verbose_name='usuario'),
        ),
    ]
