# Generated by Django 5.1.1 on 2024-09-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='precio',
        ),
    ]
