# Generated by Django 5.1.1 on 2024-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_receta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.JSONField(default=list, verbose_name='ingredientes'),
        ),
    ]
