# Generated by Django 5.1.1 on 2024-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_receta_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
