# Generated by Django 5.1.1 on 2024-11-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_receta_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='category',
        ),
        migrations.AddField(
            model_name='receta',
            name='category',
            field=models.ManyToManyField(related_name='recetas', to='blog.category'),
        ),
    ]
