# Generated by Django 5.1.1 on 2024-10-07 01:53

import blog.validadores.validador_receta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_receta_cantidades_alter_receta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='cantidades',
            field=models.JSONField(validators=[blog.validadores.validador_receta.validate_cantidades], verbose_name='cantidades'),
        ),
    ]
