# Generated by Django 5.1.1 on 2024-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_receta_category_receta_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/', verbose_name='Imagen'),
        ),
    ]
