# Generated by Django 5.1.1 on 2024-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='unidad'),
        ),
    ]
