# Generated by Django 5.1.1 on 2024-11-15 23:01

import blog.validadores.validador_receta
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_ingrediente_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000), blog.validadores.validador_receta.validate_no_html], verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='category',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
    ]
