# Generated by Django 5.1.1 on 2024-11-19 01:32

import blog.validadores.validador_receta
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_descripcion_category_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='puntuacion',
            field=models.FloatField(blank=True, validators=[blog.validadores.validador_receta.validate_between_zero_and_five], verbose_name='puntuacion'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(verbose_name='puntuacion')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.receta', verbose_name='receta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='cedula', verbose_name='usuario')),
            ],
        ),
    ]
