# Generated by Django 5.1.1 on 2024-11-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_receta_puntuacion_valoracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name_plural': 'valoraciones'},
        ),
    ]
