# Generated by Django 5.1.1 on 2024-11-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_favoritos'),
        ('blog', '0010_alter_valoracion_options'),
    ]

    operations = [
    ]
