# Generated by Django 5.1.1 on 2024-11-21 20:14

import blog.validadores.validador_receta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_0009_favoritos_0010_alter_valoracion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='puntuacion',
            field=models.FloatField(blank=True, default=0, validators=[blog.validadores.validador_receta.validate_between_zero_and_five], verbose_name='puntuacion'),
        ),
    ]
