# Generated by Django 5.1.1 on 2024-10-28 18:31

import django.core.validators
import ecommerce.validadores.validador_ingrediente
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[ecommerce.validadores.validador_ingrediente.validar_solo_letras], verbose_name='nombre')),
                ('unidad', models.CharField(max_length=50, validators=[ecommerce.validadores.validador_ingrediente.unidad], verbose_name='unidad')),
                ('cantidad_disponible', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='cantidad_disponible')),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='precio')),
                ('unidades_vendidas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='unidades_vendidas')),
            ],
        ),
    ]
