# Generated by Django 5.1.1 on 2024-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ingredientes',
            field=models.JSONField(default=list),
        ),
    ]
