# Generated by Django 5.1.1 on 2024-10-29 01:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, unique=True)),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='cedula', verbose_name='facturas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFacturado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='cantidad')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.factura', verbose_name='productos_facturados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto', verbose_name='productos_facturados')),
            ],
        ),
    ]
