# Generated by Django 5.1.1 on 2024-09-29 17:43

import django.core.validators
import ecommerce.validadores.validador_factura
import ecommerce.validadores.validador_ingrediente
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_factura_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cedula',
            field=models.IntegerField(validators=[ecommerce.validadores.validador_factura.cedula_longitud]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_disponible',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='cantidad_disponible'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[ecommerce.validadores.validador_ingrediente.validar_solo_letras], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(max_length=50, validators=[ecommerce.validadores.validador_ingrediente.unidad], verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidades_vendidas',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='unidades_vendidas'),
        ),
    ]
