# Generated by Django 5.1.3 on 2024-11-18 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofacturado',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='subtotal'),
        ),
    ]
