# Generated by Django 5.1.1 on 2024-10-01 18:21

import ecommerce.validadores.validador_factura
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_factura_cedula_alter_factura_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidades',
            field=models.JSONField(default=list, validators=[ecommerce.validadores.validador_factura.validate_cantidades], verbose_name='cantidades'),
        ),
        migrations.RemoveField(
            model_name='factura',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='factura',
            name='ingredientes',
            field=models.ManyToManyField(to='ecommerce.ingrediente', verbose_name='ingredientes'),
        ),
    ]
