# Generated by Django 5.1.1 on 2024-10-01 18:38

import ecommerce.validadores.validador_factura
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_factura_cantidades_remove_factura_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='formaPago',
            field=models.CharField(default='nada', max_length=255, validators=[ecommerce.validadores.validador_factura.validar_solo_letras_con_espacio]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='nombreCliente',
            field=models.CharField(default='nada', max_length=255, validators=[ecommerce.validadores.validador_factura.validar_solo_letras_con_espacio]),
            preserve_default=False,
        ),
    ]
