# Generated by Django 5.1.1 on 2024-10-07 15:49

import ecommerce.validadores.validador_factura
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_factura_formapago_factura_nombrecliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidades',
            field=models.JSONField(validators=[ecommerce.validadores.validador_factura.validate_cantidades], verbose_name='cantidades'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
