# Generated by Django 5.1.1 on 2024-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('contraseña', models.CharField(max_length=255, verbose_name='contraseña')),
                ('cedula', models.IntegerField(verbose_name='cedula')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('correro', models.EmailField(max_length=255, verbose_name='correo')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('cargo', models.CharField(max_length=255, verbose_name='cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('contraseña', models.CharField(max_length=255, verbose_name='contraseña')),
                ('cedula', models.IntegerField(unique=True, verbose_name='cedula')),
                ('direccion', models.TextField(verbose_name='direccion')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='correo')),
                ('telefono', models.BigIntegerField(blank=True, null=True, verbose_name='telefono')),
                ('favoritos', models.JSONField(blank=True, null=True, verbose_name='favoritos')),
            ],
        ),
    ]
