# Generated by Django 5.1.1 on 2024-09-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'trabajadores'},
        ),
    ]
