# Generated by Django 5.1.1 on 2024-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_trabajador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cedula',
            field=models.IntegerField(unique=True, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correro',
            field=models.EmailField(max_length=255, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(default=0, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
