# Generated by Django 5.1.1 on 2024-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('ver_usuario', 'Puede ver los datos de los usuarios'), ('modificar_usuario', 'Puede modificar los datos de los usuarios'), ('eliminar_usuario', 'Puede eliminar usuarios'), ('ver_facturas', 'Puede ver las facturas'), ('modificar_facturas', 'Puede modificar las facturas existentes'), ('eliminar_facturas', 'Puede eliminar facturas'), ('ver_ingredientes', 'Puede ver los ingredientes'), ('crear_ingredientes', 'Puede crear nuevos ingredientes'), ('modificar_ingredientes', 'Puede modificar los ingredientes existentes'), ('eliminar_ingredientes', 'Puede eliminar ingredientes'), ('ver_recetas', 'Puede ver las recetas'), ('crear_recetas', 'Puede crear nuevas recetas'), ('modificar_recetas', 'Puede modificar las recetas existentes'), ('eliminar_recetas', 'Puede eliminar recetas'), ('puede_ver_vistas_admin', 'Puede ver las vistas pq es empleado'))},
        ),
    ]
