# Generated by Django 5.1.1 on 2024-11-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='favoritos',
        ),
    ]
