# Generated by Django 5.1.1 on 2024-10-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login3', '0002_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('puede_ver_vistas_admin', 'Puede ver vistas administrativas'),)},
        ),
    ]
